# Generated by Django 3.2.6 on 2021-08-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='Description'),
            preserve_default=False,
        ),
    ]
