# Generated by Django 3.2.6 on 2021-09-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_room_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
